apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: adguardhome-sync-credentials
  namespace: infra
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: adguardhome-sync-credentials
  data:
    # Origin = nasus AdGuard (10.0.40.3) - currently the source of truth - primary
    - secretKey: origin-password
      remoteRef:
        key: secret/adguard/sync
        property: origin-password
    # Replica = Ryze Pi AdGuard (10.0.40.3) - currently the source of truth - secondary
    - secretKey: replica-password
      remoteRef:
        key: secret/adguard/sync
        property: replica-password
