apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hindsight
  namespace: apps
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: hindsight
  data:
    - secretKey: HINDSIGHT_API_LLM_API_KEY
      remoteRef:
        key: { { .Values.externalSecret.key } }
        property: { { .Values.externalSecret.property } }
    - secretKey: HINDSIGHT_CP_ACCESS_KEY
      remoteRef:
        key: { { .Values.externalSecret.key } }
        property: { { .Values.externalSecret.accessKeyProperty } }
