apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hindsight-data
  namespace: apps
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.storage.storageClass }}
  resources:
    requests:
      storage: {{ .Values.storage.size }}
